AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'omni-serverless

  Sample SAM Template for omni-serverless

  '
Globals:
  Function:
    Timeout: 5
Resources:
  CuencaShippingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://omni-serverless.cuenca.io/64b65d2f3f116974bbd59fc6eb214384
      Handler: app.cuenca_shipping
      Runtime: python3.7
      Environment:
        Variables:
          MONGO_URI: mongodb://0.0.0.0:27017/
          CORS_ORIGIN: http://0.0.0.0:9000
      Events:
        CuencaShipping:
          Type: Api
          Properties:
            Path: /cuenca-shipping/address
            Method: post
        CuencaShippingCors:
          Type: Api
          Properties:
            Path: /cuenca-shipping/address
            Method: options
  BotmakerMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://omni-serverless.cuenca.io/a42dcc73f0519a51768522afdc413f5e
      Handler: app.botmaker_message
      Runtime: python3.7
      Environment:
        Variables:
          MONGO_URI: mongodb://0.0.0.0:27017/
          SANDBOX_MODE: false
          SANDBOX_URL: https://example.com
      Events:
        CuencaShipping:
          Type: Api
          Properties:
            Path: /botmaker/message
            Method: post
Outputs:
  CuencaShippingApi:
    Description: Api Cuenca Shipping
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cuenca-shipping/address
  BotmakerMessageApi:
    Description: Api Botmaker Message
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/botmaker/message
