AWSTemplateFormatVersion: '2010-09-09'
Description: 'omni-serverless

  Sample SAM Template for omni-serverless

  '
Globals:
  Function:
    Timeout: 5
Outputs:
  BotmakerMessageApi:
    Description: Api Botmaker Message
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/botmaker/message
  CuencaShippingApi:
    Description: Api Cuenca Shipping
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cuenca-shipping/address
Resources:
  BotmakerMessageFunction:
    Properties:
      CodeUri: s3://omni-serverless.cuenca.io/5b335ca0ccdd2eb974aa082724e638c8
      Environment:
        Variables:
          MONGO_URI: mongodb://0.0.0.0:27017/
      Events:
        CuencaShipping:
          Properties:
            Method: post
            Path: /botmaker/message
          Type: Api
      Handler: app.botmaker_message
      Runtime: python3.7
    Type: AWS::Serverless::Function
  CuencaShippingFunction:
    Properties:
      CodeUri: s3://omni-serverless.cuenca.io/18f0bd0d0ca91cf661862ed0a7372fb1
      Environment:
        Variables:
          CORS_ORIGIN: http://0.0.0.0:9000
          MONGO_URI: mongodb://0.0.0.0:27017/
      Events:
        CuencaShipping:
          Properties:
            Method: post
            Path: /cuenca-shipping/address
          Type: Api
        CuencaShippingCors:
          Properties:
            Method: options
            Path: /cuenca-shipping/address
          Type: Api
      Handler: app.cuenca_shipping
      Runtime: python3.7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
