AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  omni-serverless

  Sample SAM Template for omni-serverless

Globals:
  Function:
    Timeout: 5

Resources:
  CuencaShippingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cuenca_shipping/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          MONGO_URI: mongodb://0.0.0.0:27017/
          CORS_ORIGIN: http://0.0.0.0:9000
      Events:
        CuencaShipping:
          Type: Api
          Properties:
            Path: /cuenca-shipping/address
            Method: post
        CuencaShippingCors:
          Type: Api
          Properties:
            Path: /cuenca-shipping/address
            Method: options
  BotmakerMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: botmaker_message/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          MONGO_URI: mongodb://0.0.0.0:27017/
      Events:
        CuencaShipping:
          Type: Api
          Properties:
            Path: /botmaker/message
            Method: post

Outputs:
  CuencaShippingApi:
    Description: "Api Cuenca Shipping"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cuenca-shipping/address"
  BotmakerMessageApi:
    Description: "Api Botmaker Message"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/botmaker/message"
